[package]
name = "driverwrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
drivers = { git = "https://github.com/0xb-s/drivers" }
embedded-hal-async = "1.0.0"
heapless = "0.8.0"
smart-leds = "0.4.0"
